Story1
timyop/Endangered-animals pull request #5
Opened 2022-08-03 10:54 UTC by timyop

This has been Unit tested, browser tested, accessibility tested and is responsive. hope it meets ur requirements and here if you have any questions

2022-08-03 10:57 UTC, norayna commented on Style.css
> +
empty line - delete

2022-08-03 10:57 UTC, norayna commented on Style.css
> +   width: 100vw;
indent missing 1 space on this line

2022-08-03 10:59 UTC, norayna commented on functions.php
> +function dbpull():array{
should be `dbPull()` - camelcase everywhere

2022-08-03 11:00 UTC, norayna commented on functions.php
> +    $allresults = $query->fetchAll();
should be `$allResults` - camelcase everywhere

2022-08-03 11:01 UTC, norayna commented on functions.php
> +$animals = dbpull();
this line needs to be removed - it already runs in `index.php`

2022-08-03 11:02 UTC, norayna commented on functions.php
> +function displayAnimals(array $animals):string {
needs a space before `string`:
```php
function displayAnimals(array $animals): string {
```

2022-08-03 11:03 UTC, norayna commented on functions.php
> +     return $animalsHTML;
indentation is weird in this function - i recommend doing Code > Reformat code in phpstorm to fix the indents in the whole file

2022-08-03 11:03 UTC, norayna commented on functions.php
> +     foreach ($animals as $animal){
need a space before the {

2022-08-03 11:04 UTC, norayna commented on functions.php
> +function dbpull():array{
also better to rename to `pullAllAnimalsFromDb()` or something like that - makes it a bit easier to tell exactly what it does

2022-08-03 11:08 UTC, norayna commented on index.php
> +    <h1>ENDANGERED ANIMAL LIST</h1>
all caps should be done using css, the html code should be like this:
```html
<h1>Endangered Animals List</h1>
```

2022-08-03 11:09 UTC, norayna commented on index.php
> +    <link rel="stylesheet" type="text/css" href="Style.css">
your file `Style.css` should be renamed to `style.css`

2022-08-03 11:09 UTC, norayna commented on index.php
> +        echo displayAnimals($animals);
this line should be indented 1 more tab inwards

2022-08-03 11:13 UTC, norayna commented on test/functions.php
> +    public function testDisplayAnimalsSuccess()
better name would be `testDisplayAnimalsSuccessString` and the other one `testDisplayAnimalsSuccessCorrectOutput`

2022-08-03 11:13 UTC, norayna commented on test/functions.php
> +
delete empty line

2022-08-03 11:25 UTC, norayna commented on Style.css
> +    width: 100vw;
better to use 100% rather than vw

2022-08-03 11:28 UTC, norayna commented on index.php
> +    </div>
this div can be removed (as discussed)

2022-08-03 12:33 UTC, norayna commented on Style.css
> +    margin: 0 auto;
what's the purpose of this line?

2022-08-03 12:46 UTC, norayna requested changes
upon reflection, i think you need to change up your html tags because `ul` and `li` are not really used in this way normally. here is my suggestion:

note that also the link is a different colour so that way it looks clickable. at the moment it's almost hidden
![image](https://user-images.githubusercontent.com/25844355/182611131-efa2e5cd-e509-4d94-85a0-ef57acbb2ab5.png)

2022-08-04 10:34 UTC, nealioa requested changes

2022-08-04 10:34 UTC, nealioa commented on functions.php
> +    $queryString = 'SELECT * FROM `animals`;';
Replace the * with actual names of columns (in backticks).

An * is not recommended in production code.

2022-08-04 10:34 UTC, nealioa commented on functions.php
> +            !array_key_exists('charity', $animal)) {
Change this to
```
    !array_key_exists('charity', $animal)
) {
```

2022-08-04 10:34 UTC, nealioa commented on functions.php
> +}
Add a blank line after this.

2022-08-04 10:34 UTC, nealioa commented on style.css
> +    border: 3px solid black;
Replace the colour name with its hex value.

2022-08-04 10:34 UTC, nealioa commented on style.css
> +    background-color: #85144b;
To be consistent, hex values should all be uppercase or all lowercase.

2022-08-04 13:36 UTC, nealioa approved these changes

2022-08-04 13:36 UTC, merged